// <auto-generated />
using System;
using MarkaTLScript.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarkaTLScript.Migrations
{
    [DbContext(typeof(DbMarkatlScriptContext))]
    partial class DbMarkatlScriptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MarkaTLScript.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<bool?>("GameStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("game_status");

                    b.Property<bool?>("KontorStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("kontor_status");

                    b.Property<string>("SiteClosedMessage")
                        .HasColumnType("text")
                        .HasColumnName("site_closed_message");

                    b.Property<string>("SiteName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_name");

                    b.Property<bool?>("SmsStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sms_status");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("support_phone");

                    b.Property<bool?>("SystemStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("system_status");

                    b.Property<bool?>("TelegramNotificationEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("telegram_notification_enabled");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("system_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
